board/urls.py
from django.urls import path
from .views import *

app_name = "board"
urlpatterns = [
    path('board_main',board_main,name='board_main'),
    path('request_detail/<str:id>',request_detail,name='request_detail'),
    path('request_edit/<str:id>',request_edit,name='request_edit'),
    path('request_update/<str:id>',request_update,name='request_update'),
    path('request_delete/<str:id>',request_delete,name='request_delete'),
    path('request_create',request_create,name='request_create'),
    path('request_new',request_new,name='request_new'),
]

podongpodong/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from podongpodong import views


urlpatterns = [
    path('admin/', admin.site.urls), # admin
    path('', views.main, name="main"),
    path('restaurant/', include('restaurant.urls')), # 식당
    path('review/', include('review.urls')),
    path('users/',include('users.urls')),
    path('accounts/',include('allauth.urls')),
    path('board/',include('board.urls')), # 건의함
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "restaurant"
urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='restaurant_list'),
    path('<str:id>/', RestaurantList, name='restaurant_list2'),
    path('detail/<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    path('detail/<int:pk>/follow', followRestaurant, name='followRestaurant'),
    path('detail/<int:pk>/commentLike/<int:id>', likeComment, name='likeComment'),
    path('detail/<int:pk>/commentHate/<int:id>', hateComment, name='hateComment'),
    path('<int:id>/create_comment', CreateRestaurantComment, name='create_restaurant_comment'),

    # 식당 검색
    path('restaurant/search/', SearchRestaurant, name='search_resturant'),
]

review/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "review"
urlpatterns = [
    path('',views.review,name='review'),
    path('<int:id>/',views.filter,name='filter'),

    # 검색
    path('search/', views.SearchReview, name="SearchReview")
]

users/urls.py
from django.urls import path
from .import views

app_name="users"
urlpatterns = [
    path("<int:id>/mypage/", views.mypage, name="mypage"),
]

podongpodong/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, default='')
    email = models.EmailField(max_length=20,default='')
    phone = models.IntegerField(default='')


    class Meta:
        ordering = ['id']
        db_table = 'user_profile'

        verbose_name = 'User Profile'
        verbose_name_plural = 'User Profile'

    def __str__(self):
        return self.name

podongpodong/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.db import models
from .models import UserProfile

class SignupForm(forms.Form):
    class Meta:
        model = User
    
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder':''}), label="이름")
    phone = forms.IntegerField(widget=forms.TextInput(attrs={'placehoder':''}), label="전화번호")
    
    def signup(self, request, user):
        userProfile = UserProfile()
        userProfile.user = user
        userProfile.name = self.cleaned_data[('name')]
        userProfile.email = user.email
        userProfile.phone = self.cleaned_data[('phone')]
        userProfile.save()
        user.save()
        return user

podongpodong/accounts/views.py
from django.shortcuts import render

# Create your views here.

podongpodong/views.py
from django.shortcuts import render
from restaurant.views import *
from django.db.models import Count

def main(request):
  review = Comment.objects.all()
  id_arr = []
  if len(review) < 6:
    review = review.annotate(like_count = Count('like_users')).order_by("-like_count", "-created_at")
  else:
    review = review.annotate(like_count = Count('like_users')).order_by("-like_count", "-created_at")
    for i in range(6):
      id_arr.append(review[i].id)
    review = review.filter(id__in=id_arr)
  category = Category.objects.all()
  return render(request, 'mainPage.html',{'review':review, 'category':category})

podongpodong/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
  {% include 'head.html' %}

  <body>
    {% include 'header.html' %} {% block content %} {% endblock %}

    <!-- footer -->
    {% include 'footer.html' %}
    <!-- ===============================================-->
    <!--    JavaScripts-->
    <!-- ===============================================-->
    <script src="{% static 'vendors/@popperjs/popper.min.js' %}"></script>
    <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendors/is/is.min.js' %}"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
    <script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
      crossorigin="anonymous"
    ></script>

    <link
      href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@200;300;400;600;700;900&amp;display=swap"
      rel="stylesheet"
    />
  </body>
</html>

podongpodong/templates/footer.html
<!-- Footer-->

  <section class="py-0 pt-7 bg-1000">
    <div class="container">
      <div class="row">

        <div class="col-12 col-md-8 col-lg-6 col-xxl-4">
          <h5 class="lh-lg fw-bold text-500">FOLLOW US</h5>
          <div class="text-start my-3">
            <a href="https://www.instagram.com/podong_podong_2021/?utm_medium=copy_link" target="_blank">
              <i
                class="bi bi-instagram"
                style="color: white; font-size: 2em;"
              ></i>
            </a>
          </div>
        </div>
      </div>
      <hr class="border border-800" />
      <div class="row flex-center pb-3">
        <div class="col-md-6 order-0">
          <p class="text-200 text-center text-md-start">
            All rights Reserved &copy; Your Company, 2021
          </p>
        </div>
        <div class="col-md-6 order-1">
          <p class="text-200 text-center text-md-end">
            Made with&nbsp;
            <svg
              class="bi bi-suit-heart-fill"
              xmlns="http://www.w3.org/2000/svg"
              width="15"
              height="15"
              fill="#FFB30E"
              viewBox="0 0 16 16"
            >
              <path
                d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"
              ></path>
            </svg>
            &nbsp;by&nbsp;
            <a
              class="text-200 fw-bold"
              href="https://github.com/LikeLion-at-DGU/PodongPodong"
              target="_blank"
            >
              동대멋사 김수영 / 백지원 / 정재혁 / 안석환 / 오광혁 / 이슬기
            </a>
          </p>
        </div>
      </div>
    </div>
    <!-- end of .container-->
  </section>

podongpodong/templates/head.html
{% load static %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>포동포동</title>

  {% load static %}

  <!-- 식당보기 페이지 카테고리 슬라이드를 위해 Slick js 추가 -->
  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  <link
    rel="icon"
    type="image/png"
    sizes="64x64"
    href="{% static 'img/favicons/podongpodong_favicon.png' %}"
  />
  <link
    rel="shortcut icon"
    type="image/png"
    sizes="32x32"
    href="{% static 'img/favicons/podongpodong_favicon.png' %}"
  />
  <link rel="manifest" href="{% static 'img/favicons/manifest.json' %}" />
  <meta
    name="msapplication-TileImage"
    content="assets/img/favicons/mstile-150x150.png"
  />
  <meta name="theme-color" content="#ffffff" />

  <!-- ===============================================-->
  <!--    Stylesheets-->
  <!-- ===============================================-->
  <link href="{% static 'css/theme.css' %}" rel="stylesheet" />

  <!-- icon -->
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
  />

  <!-- 식당보기 페이지 카테고리 슬라이드를 위해 Slick css 추가 -->
  <link rel="stylesheet" type="text/css" href="http://kenwheeler.github.io/slick/slick/slick.css" />
  <link rel="stylesheet" type="text/css" href="http://kenwheeler.github.io/slick/slick/slick-theme.css" />

  <!-- 건의함 css-->
  <link rel = 'stylesheet' href = "{% static 'css/board.css'%}">
</head>

podongpodong/templates/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/components/header.css' %}" />

<!-- Navigation-->
<nav
  class="navbar navbar-expand-lg navbar-light bg-light fixed-top"
  data-navbar-on-scroll="data-navbar-on-scroll"
>
  <div id="head_nav" class="container">
    <a class="navbar-brand d-inline-flex" href="{% url 'main' %}">
      <img
        id="logo"
        class="d-inline-block"
        src="{% static 'img/podongpodong_logo.png' %}"
        alt="logo"
        style="width: 130px; height: 80px; margin-left: -25px; padding: 0; object-fit: cover; "
      />
      <!-- <span class="text-1000 fs-3 fw-bold ms-2 text-gradient">
        포동포동
      </span> -->
    </a>
    <button
      class="navbar-toggler"
      type="button"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- 메뉴 -->
    <div
      class="collapse navbar-collapse border-top border-lg-0 my-2 mt-lg-0"
      id="navbarSupportedContent"
    >
      <div class="mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block">
        <p class="mb-0 fw-bold text-lg-center mt-3">
          <a class="nav-link nav_item d-inline-flex" href="{% url 'restaurant:restaurant_list' %}">식당 보기</a>
        </p>
      </div>
      <div class="mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block">
        <p class="mb-0 fw-bold text-lg-center mt-3">
          <a class="nav-link nav_item" href="{% url 'review:review' %}">후기 보기</a>
        </p>
      </div>
      <div
        class="dropdown mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block"
      >
        <p class="nav-link nav_item dropbtn nav_item mb-0 fw-bold text-lg-center mt-3">
          건의함
        </p>
        <div class="dropdown-content">
          <a href="{% url 'board:request_new' %}">건의하기</a>
          <a href="{% url 'board:board_main' %}">건의 목록</a>
        </div>
      </div>
        {% if user.is_authenticated %}
          <div class="dropdown nav-link mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block">
            <p class="dropbtn nav_item mb-0 fw-bold text-lg-center mt-3">
                MY Page
            </p>
            <div class="dropdown-content">
              <a href="{% url 'users:mypage' request.user.id %}">Mypage</a></li>
              <a href="{% url 'account_logout' %}">Logout </a></li>
            </div>
          </div> 
        {% else %}
          <div class="dropdown nav-link mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block">
            <p class="dropbtn nav_item mb-0 fw-bold text-lg-center mt-3">
                Login 
            </p>
            <div class="dropdown-content">
              <a href="{%url 'account_login'%}">Login</a></li>
              <a href="{%url 'account_signup'%}">Signup</a></li>
            </div>
          </div>   
          {% endif %}
      </div>
  </div> 
</nav>
<script type="text/javascript">
  $(".navbar-toggler").click(function(e){
    e.preventDefault();
    $("#navbarSupportedContent").not(':animated').slideToggle();
  });
</script>