board/urls.py
from django.urls import path
from .views import *

app_name = "board"
urlpatterns = [
    path('board_main',board_main,name='board_main'),
    path('request_detail/<str:id>',request_detail,name='request_detail'),
    path('request_edit/<str:id>',request_edit,name='request_edit'),
    path('request_update/<str:id>',request_update,name='request_update'),
    path('request_delete/<str:id>',request_delete,name='request_delete'),
    path('request_create',request_create,name='request_create'),
    path('request_new',request_new,name='request_new'),
]

podongpodong/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from podongpodong import views


urlpatterns = [
    path('admin/', admin.site.urls), # admin
    path('', views.main, name="main"),
    path('restaurant/', include('restaurant.urls')), # 식당
    path('review/', include('review.urls')),
    path('users/',include('users.urls')),
    path('accounts/',include('allauth.urls')),
    path('board/',include('board.urls')), # 건의함
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=2000)
    cafeteria = models.CharField(max_length=2000)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField()
    body = models.TextField()
    
    def __str__(self):
        return self.title

board/views.py
from django.shortcuts import render,get_object_or_404,redirect
from board.models import *
from django.utils import timezone

# Create your views here.
def board_main(request):
    boards = Board.objects.all().order_by('-date')
    return render(request,'board/board_main.html',{'boards':boards})

def request_detail(request,id):
    board = get_object_or_404(Board,pk=id)
    return render(request,'board/request_detail.html',{'board':board})

def request_new(request):
    return render(request,'board/request_new.html')

def request_create(request):
    request_new_post = Board()
    request_new_post.title = request.POST['title']
    request_new_post.cafeteria = request.POST['cafeteria']
    request_new_post.writer = request.user
    request_new_post.date = timezone.now()
    request_new_post.body = request.POST['body']
    request_new_post.save()
    return redirect('board:request_detail',request_new_post.id)

def request_edit(request,id):
    request_edit_post = Board.objects.get(id = id)
    return render(request, 'board/request_edit.html', {'board':request_edit_post})

def request_update(request,id):
    request_update_post = get_object_or_404(Board, id = id)
    request_update_post.title = request.POST['title']
    request_update_post.cafeteria = request.POST['cafeteria']
    request_update_post.writer = request.user
    request_update_post.date = timezone.now()
    request_update_post.body = request.POST['body']
    request_update_post.save()
    return redirect('board:request_detail',request_update_post.id)

def request_delete(request,id):
    request_delete_post = Board.objects.get(id = id)
    request_delete_post.delete()
    return redirect('board:board_main')

board/templates/board/board_main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/board.css'%}?ab">

<section class="py-0 bg-primary-gradient">
    <div class = 'container'>
        <div class="row justify-content-center g-0">
            <div class="col-xl-9">
                <div class="col-lg-6 text-center mx-auto mb-3 mb-md-5 mt-4">
                    <h5 class="fw-bold text-danger fs-3 fs-lg-5 lh-sm my-6" style="margin-top:8rem !important;">식당 건의함</h5>
                </div>
                <div class = "board_main">
                    <a href = "{% url 'board:request_new' %}"><button class="btn btn-danger" style="padding:0.5rem;" type="submit">
                        글쓰기
                      </button></a>
                    <table class="table table-striped d-block d-sm-none">
                        <thead>
                            <tr class="thead col-xs-1">
                                <th scope="col" id = 'board_title'>제목</th>
                                <th scope='col' id = 'board_cafeteria' width=30%>식당 이름</th>
                                <th scope="col" id = 'board_writer'>작성자</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for board in boards %}
                            <tr>
                                <td><a id = 'board_title_a' href="{% url 'board:request_detail' board.id %}">{{board.title|truncatechars:7}}</a></td>
                                <td>{{board.cafeteria}}</td>
                                <td>{{board.writer}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                      </table>
                      <!--모바일 이외의 화면에서만 보임-->
                      <table class="table d-none d-sm-table">
                        <thead>
                            <tr class="thead col-xs-1">
                                <th scope="col" id = 'board_num'>순번</th>
                                <th scope="col" id = 'board_title'>제목</th>
                                <th scope='col' id = 'board_cafeteria'>식당 이름</th>
                                <th scope="col" id = 'board_writer'>작성자</th>
                                <th scope="col" id = 'board_date'>작성날짜</th>
                        </thead>
                        <tbody>
                            {% for board in boards %}
                            <tr>
                                <td>{{ forloop.revcounter }}</td>
                                <td><a id = 'board_title_a' href="{% url 'board:request_detail' board.id %}">{{board.title}}</a></td>
                                <td>{{board.cafeteria}}</td>
                                <td>{{board.writer}}</td>
                                <td>{{board.date}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                      </table>
                </div>
            </div>
        
        </div>
        <div class="page middle">
            {% if pages.has_previous %}
            <a href="?page={{pages.previous_page_number}}" class="page_click active">◀ 이전</a>
            {% else %}
            <a class="page_click nonactive">◀ 이전</a>
            {% endif %}
        
            {% if pages.has_next %}
            <a href="?page={{pages.next_page_number}}" class="page_click active">다음 ▶</a>
            {% else %}
            <a class="page_click nonactive">다음 ▶</a>
            {% endif %}
        </div>
    </div>
</section>

<script>
$(".hover").mouseleave(
  function() {
    $(this).removeClass("hover");
  }
);
</script>
<style>
    th, td {
        text-align: left;
    }
    .thead {
      border-bottom:#F17228;
    }
    .bnt {
      background-color: #F17228; 
      color: white; 
      font-weight: bold; 
      border: none; 
      border-radius: 5px; width: 80px;
    }
    section {
  margin-top: 100px;
  min-height: 400px;
}
.middle{
  text-align: center;
  margin-bottom: 5%;
}
.middle a {
  margin: 20px;
  padding: 10px;
}
.number {
  font-size: 20px;
}
.active {
  transition-duration: 0.2s;
}
.active:hover {
  color: #FFB310;
  cursor: pointer;
}
.nonactive {
  color: #a4a4a4;
  cursor: pointer;
}
  </style>

{% endblock %}

board/templates/board/request_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section>
    <div class = 'container'>
        <div class="row">
        <div class='board_content text-center' style="margin-top: 100px;">
        <i class="far fa-file-alt" style="color: #F17228; font-size: 30px;"></i>
        <div class="fw-bold text-center text-danger fs-3 fs-lg-5 lh-sm my-3" style="display:inline-block;">{{board.title}}</div>
        </div>
        <div class="col-lg-2">
        </div>
        <div class="col-lg-8">
        <strong>작성자 : </strong>{{board.writer}}<br>
        <strong>날짜 :</strong> {{board.date}}
        <p><strong>식당 이름:</strong> {{board.cafeteria}}</p>
        <hr style="height: 3px; color:#F17228;">
        <p>{{board.body}}</p>
        <div class = 'board_detail' style="text-align: center; margin-top:20%;">
    {% if user == board.writer %}
            <a href="{% url 'board:request_edit' board.id %}"><button style="width: 100px; color: #fff;">수정</button></a> &nbsp;
            <a href="{% url 'board:request_delete' board.id %}"><button style="width: 100px; color: #fff;">삭제</button></a> &nbsp; 
            <a href="{% url 'board:board_main' %}"><button style="width: 100px; color: #fff;">돌아가기</button></a>
        </div>
    {% else %}
            <a href="{% url 'board:board_main' %}"><button style="width: 100px; color: #fff;">돌아가기</button></a>
        </div>
    {% endif %}
        <div class="col-lg-2"></div>
    </div>
    </div>
</section>
{% endblock %}

board/templates/board/request_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section>
<div class='board_content text-center' style="margin-top: 100px;">
    <i class="far fa-edit" style="color: #F17228; font-size: 30px;"></i>
    <div class="fw-bold text-center text-danger fs-3 fs-lg-5 lh-sm my-3" style="display:inline-block;">글 수정하기</div>
    </div><br>

<div class = 'container'>
    <div class = 'board_new'>
        <form action = "{%url 'board:request_update' board.id %}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            <p>제목</p>
            <input type="text" name="title" value="{{board.title}}" style="width:100%">
            <p>식당 이름</p>
            <input type="text" name="cafeteria" value="{{board.cafeteria}}" style="width:100%">
            <p>비고</p>
            <textarea name="body" cols="50" rows="10" style="width: 100%;">{{board.body}}</textarea>
            <br><br>
            <div style="text-align: center;">
                <button type='submit' style = 'font-size:18px; width:20%; color: white;'>제출</button>
            </div>
        </form>
    </div>
</div>
</section>

{% endblock %}

board/templates/board/request_new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section>
    <div class='board_content text-center' style="margin-top: 100px;">
        <i class="far fa-edit" style="color: #F17228; font-size: 30px;"></i>
        <div class="fw-bold text-center text-danger fs-3 fs-lg-5 lh-sm my-3" style="display:inline-block;">글 작성하기</div>
        </div><br>
    {% if user.is_authenticated %}

    <div class = 'container'>
        <div class = 'board_new'>
            <form action = "{% url 'board:request_create' %}" method="POST">
                {%csrf_token%}
                <p id = "new"><strong>제목</strong></p>
                <input type="text"  name="title" placeholder="제목을 입력해주세요" style="width:100%">
                <p id = "new"><strong>식당 이름</strong></p>
                <input type="text"  name="cafeteria" placeholder="식당 이름을 입력해주세요" style="width:100%">
                <p id = "new"><strong>비고</strong></p>
                <textarea name="body" cols="50" rows="10" style="width: 100%;"></textarea>
                <br><br>
                <div style="text-align: center;">
                <button type='submit' style = 'font-size:18px; width:20%; color: white;'>제출</button>
                </div>
            </form>
        </div>
    </div>

    {% else %} 
        <div class = "board_authentication">
            <h3> 로그인 후 글 등록 가능</h3>
            <br><br>
            <a href = "{% url 'account_login' %}"  class="btn btn-warning">로그인</a>&nbsp;&nbsp;&nbsp;&nbsp;
            <a href = "{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        </div>
    {% endif %}
    </div>
</section>
{% endblock %}