board/urls.py
from django.urls import path
from .views import *

app_name = "board"
urlpatterns = [
    path('board_main',board_main,name='board_main'),
    path('request_detail/<str:id>',request_detail,name='request_detail'),
    path('request_edit/<str:id>',request_edit,name='request_edit'),
    path('request_update/<str:id>',request_update,name='request_update'),
    path('request_delete/<str:id>',request_delete,name='request_delete'),
    path('request_create',request_create,name='request_create'),
    path('request_new',request_new,name='request_new'),
]

podongpodong/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from podongpodong import views


urlpatterns = [
    path('admin/', admin.site.urls), # admin
    path('', views.main, name="main"),
    path('restaurant/', include('restaurant.urls')), # 식당
    path('review/', include('review.urls')),
    path('users/',include('users.urls')),
    path('accounts/',include('allauth.urls')),
    path('board/',include('board.urls')), # 건의함
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "restaurant"
urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='restaurant_list'),
    path('<str:id>/', RestaurantList, name='restaurant_list2'),
    path('detail/<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    path('detail/<int:pk>/follow', followRestaurant, name='followRestaurant'),
    path('detail/<int:pk>/commentLike/<int:id>', likeComment, name='likeComment'),
    path('detail/<int:pk>/commentHate/<int:id>', hateComment, name='hateComment'),
    path('<int:id>/create_comment', CreateRestaurantComment, name='create_restaurant_comment'),

    # 식당 검색
    path('restaurant/search/', SearchRestaurant, name='search_resturant'),
]

restaurant/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


# 식당분류 모델
class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name


# 식당 모델
# 식당 기본 정보 : 식당분류, 가게이름, 위치, 전화번호, 오픈시간, 가게사진, 팔로우
class Restaurant(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    location = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    business_hour = models.CharField(max_length=150, blank=True)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    follow_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="follow_restaurants")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('restaurant:restaurant_detail', args=[self.id])


# 메뉴 모델
# 메뉴 기본 정보 : 식당, 메뉴이름, 가격, 음식사진
class FoodMenu(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    price = models.CharField(max_length=20)

    def __str__(self):
        return self.name


# 후기 모델
# 후기 기본 정보 : 식당, 메뉴, 작성일, 음식사진, 추천, 비추천, 후기를 쓴 사용자
class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    menu = models.ForeignKey(FoodMenu, on_delete=models.CASCADE)
    content = models.TextField()
    thumbnail = models.ImageField(upload_to='comment/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="like_comments")
    hate_users = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="hate_comments")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

restaurant/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import ListView, DetailView
from restaurant.models import Category, Restaurant, FoodMenu, Comment

from django.db.models import Q
from django.core.paginator import Paginator


# 식당보기 > 식당 리스트가 나오는 페이지
class RestaurantListView(ListView):
    # 어떤 테이블에서 객체 리스트를 가져올 것인지 지정해주기
    model = Restaurant
    # 템플릿 파일로 넘겨주는 객체 리스트의 이름 지정
    context_object_name = 'restaurant_list'
    # 템플릿 파일 위치 지정
    template_name = 'restaurant/category.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # 현재 선택된 식당 분류
        context['category'] = Category.objects.all()
        # 선택된 식당 분류에 해당하는 식당 목록
        restaurant = Restaurant.objects.all()

        page = self.request.GET.get('page', '1')
        paginator = Paginator(restaurant, '10')
        restaurant = paginator.page(page)

        context['restaurant_list'] = restaurant
        return context


# 식당보기 > 식당 리스트가 나오는 페이지 (선택한 카테고리별 메뉴가 나오도록)
def RestaurantList(request, id):
    category = Category.objects.all()
    restaurant = Restaurant.objects.all()
    if id:
        current_category = get_object_or_404(Category, id=id)
        restaurant = Restaurant.objects.filter(category=current_category)

    page = request.GET.get('page', '1')
    paginator = Paginator(restaurant, '10')
    restaurant = paginator.page(page)

    context = {'category': category, 'restaurant_list': restaurant}
    return render(request, 'restaurant/category.html', context)


# 식당 상세보기 : 식당의 기본 정보, 메뉴 목록, 후기 목록 load
class RestaurantDetailView(DetailView):
    model = Restaurant
    context_object_name = 'restaurant_detail'
    template_name = 'restaurant/restaurant.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # 현재 선택된 식당
        context['restaurant'] = self.restaurant
        # 현재 선택된 식당의 메뉴 목록
        context['menu_list'] = FoodMenu.objects.filter(restaurant=self.restaurant)
        # 현재 선택된 식당에 대한 후기 목록
        context['comment_list'] = Comment.objects.filter(restaurant=self.restaurant)
        return context

    def get(self, request, *args, **kwargs):
        if 'pk' in kwargs:
            self.restaurant = Restaurant.objects.get(pk=kwargs['pk'])
        return super().get(request, *args, **kwargs)


# 식당 후기 등록
@login_required
def CreateRestaurantComment(request, id):
    if request.method == "POST":
        restaurant = get_object_or_404(Restaurant, id=id)
        review_content = request.POST.get('review_content')
        review_menu = request.POST.get('review_menu')
        menu = get_object_or_404(FoodMenu, id=review_menu)
        review_image = request.FILES.get('review_image')
        review_user = request.user
        Comment.objects.create(restaurant=restaurant, menu=menu, content=review_content, thumbnail=review_image, user=review_user)
    return redirect('restaurant:restaurant_detail', id)


# 식당명 검색
def SearchRestaurant(request):
    # 카테고리
    category = Category.objects.all()
    # 검색어 가져오기
    search_key = request.GET.get('search_key')
    # 해당 검색어를 포함한 query 가져오기
    if search_key:
        list = Restaurant.objects.filter(Q(name__icontains=search_key)).distinct().order_by('-id')
    else:
        list = Restaurant.objects.all()
    paginator = Paginator(list, 10)
    page = request.GET.get("page") or 1
    pages = paginator.get_page(page)
    return render(request, 'restaurant/search.html', { 'restaurant_list': list, "search_key": search_key, "pages": pages, "category": category })


# 식당 팔로우 하기
@login_required
def followRestaurant(request, pk):
    restaurant = get_object_or_404(Restaurant, pk=pk)
    if request.user in restaurant.follow_users.all():
        restaurant.follow_users.remove(request.user)
    else:
        restaurant.follow_users.add(request.user)
    return redirect('restaurant:restaurant_detail', pk)


# 식당의 후기에 추천 하기
@login_required
def likeComment(request, pk, id):
    comment = get_object_or_404(Comment, id=id)
    if request.user in comment.like_users.all():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('restaurant:restaurant_detail', pk)


# 식당의 후기에 비추천 하기
@login_required
def hateComment(request, pk, id):
    comment = get_object_or_404(Comment, id=id)
    if request.user in comment.hate_users.all():
        comment.hate_users.remove(request.user)
    else:
        comment.hate_users.add(request.user)
    return redirect('restaurant:restaurant_detail', pk)

restaurant/templates/restaurant/category.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<section id="testimonial">
    <div class="container">
        <div class="row h-100">
            <div class="col-lg-7 mx-auto text-center mb-3 mt-5">
                <div class="responsive">
                    <a href="{% url 'restaurant:restaurant_list' %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                        전체
                    </a>
                    {% for category in category %}
                        <a href="{% url 'restaurant:restaurant_list2' category.id %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <form action="{% url 'restaurant:search_resturant' %}" method="GET" class="row gx-2 gy-2 align-items-center mb-3">
            <table width="90%" align="center">
                <tr>
                    <td width="70%;">
                        <i class="fas fa-search input-box-icon text-primary"></i>
                        <input
                            class="col-lg-3 form-control border-0 input-box bg-100"
                            style="display: inline; width:80%;"
                            type="search"
                            placeholder="Search Restaurant"
                            aria-label="Search"
                            name="search_key"
                            id="search_key"
                            value="{{ search_key }}"
                        />
                    </td>
                    <td width="20%;">
                        <button class="btn btn-danger" type="submit" style="padding: 0.5rem;">
                            검색
                        </button>
                    </td>
                </tr>
            </table>
        </form>
        <!-- 식당 리스트 -->
        <table width="90%" align="center">
        {% for restaurant in restaurant_list %}
            <tr style="border-bottom: 1px solid #dee2e6;">
                <td style="width: 30%; padding: 10px;">
                    {% if restaurant.thumbnail %}
                    <a href="{{ restaurant.get_absolute_url }}" >
                        <img src="{{ restaurant.thumbnail.url }}" style="max-width: 80%; border-radius: 5px;">
                    </a>
                    {% else %}
                        <img src="{% static 'img/gallery/logo_black.png' %}" style="max-width: 80%; border-radius: 5px;">
                    {% endif %}
                </td>
                <td style="width: 70%; padding: 15px;">
                    <a href="{{ restaurant.get_absolute_url }}" >
                        <h5>{{ restaurant.name }}</h5>
                        <p class="mb-1">
                            <span class="text-primary fs--1 me-1">
                                <i class="fas fa-location-arrow"></i>
                            </span>
                            {{ restaurant.location }}
                        </p>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </table>

        <div id="paging">
            <ul class="pagination justify-content-center" style="margin-top: 2rem;">
                <!-- 이전페이지 -->
                {% if restaurant_list.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ restaurant_list.previous_page_number }}">이전</a>
                    </li>
                {% endif %}

            <!-- 페이지리스트 -->
            {% for page_number in restaurant_list.paginator.page_range %}
                {% if page_number == restaurant_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
            {% endfor %}


                <!-- 다음페이지 -->
                {% if restaurant_list.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ restaurant_list.next_page_number }}">다음</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</section>

<script type="text/javascript">
    $('.responsive').slick({
        dots: false,
        infinite: false,
        speed: 300,
        slidesToShow: 6,
        slidesToScroll: 1,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 6,
                    slidesToScroll: 1
                }
            },
            {
                breakpoint: 600,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 2
                    }
                },
            {
            breakpoint: 480,
                settings: {
                    slidesToShow: 4,
                    slidesToScroll: 2
                }
            }
        ]
    });
</script>

{% endblock %}

restaurant/templates/restaurant/restaurant.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% load humanize %}


<section id="testimonial">
    <div class="container">
        <div class="row h-100">
            <div class="col-lg-7 mx-auto mb-6">
                    <div class="card mb-4">
                        <div class="row g-0">
                            <div class="col-md-4">
                                {% if restaurant.thumbnail %}
                                    <img src="{{ restaurant.thumbnail.url }}" class="img-fluid rounded" width="100%">
                                {% else %}
                                    <img src="{% static 'img/gallery/logo_black.png' %}" class="img-fluid rounded" width="80%">
                                {% endif %}
                            </div>
                            <div class="col-md-7">
                                <div class="card-body">
                                    <p style="margin-bottom: 0.5em;">
                                        <span>
                                        {{ restaurant.name }}
                                        </span>
                                        <span style="margin-left: 80%;">
                                            {% with restaurant_follow_users=restaurant.follow_users.all %}
                                                {% if request.user in restaurant_follow_users %}
                                                    <a href="{% url 'restaurant:followRestaurant' restaurant.id %}">
                                                    <i class="fas fa-heart fa-sm animated delay-1s" style="color: red;"></i>
                                                    </a>
                                                {% elif user.is_authenticated %}
                                                    <a href="{% url 'restaurant:followRestaurant' restaurant.id %}">
                                                    <i class="far fa-heart fa-sm animated infinite bounce delay-1s" style="color: gray;"></i>
                                                    </a>
                                                {% else %}
                                                    <i class="far fa-heart fa-sm animated infinite bounce delay-1s" style="color: gray;"></i>
                                                {% endif %}
                                            {% endwith %}
                                        </span>
                                    </p>
                                    {% if restaurant.location %}
                                    <p style="margin-bottom: 0.5em;">
                                        <span class="text-primary fs--1 me-1">
                                            <i class="fas fa-location-arrow"></i>
                                        </span>
                                        {{ restaurant.location }}
                                    </p>
                                    {% endif %}
                                    {% if restaurant.phone_number %}
                                    <p style="margin-bottom: 0.5em;">
                                        <span class="text-primary fs--1 me-1">
                                            <i class="fas fa-phone-alt"></i>
                                        </span>
                                        {{ restaurant.phone_number }}
                                    </p>
                                    {% endif %}
                                    {% if restaurant.business_hour %}
                                    <p style="margin-bottom: 0;">
                                        <span class="text-primary fs--1 me-1">
                                            <i class="fas fa-clock"></i>
                                        </span>
                                        {{ restaurant.business_hour }}
                                    </p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>

                <!-- 메뉴, 후기 NAV TAB 영역 -->
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                        <button class="nav-link active" id="nav-menu-tab" data-bs-toggle="tab" data-bs-target="#nav-menu" type="button" role="tab" aria-controls="nav-menu" aria-selected="true">M E N U</button>
                        <button class="nav-link" id="nav-review-tab" data-bs-toggle="tab" data-bs-target="#nav-review" type="button" role="tab" aria-controls="nav-review" aria-selected="false">R E V I E W</button>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-menu" role="tabpanel" aria-labelledby="nav-menu-tab" style="padding : 1em;">
                        <!-- 메뉴 NAV 영역 -->
                        <table width="100%;">
                        {% for food in menu_list %}
                            <tr style="border-bottom: 1px solid #dee2e6;">
                                <td style="padding:15px;">{{ food.name }}</td>
                                <td style="padding:15px;" align="right">₩ {{ food.price | intcomma }}</td>
                            </tr>
                        {% endfor %}
                        </table>
                    </div>
                    <!-- END 메뉴 TAB 영역 -->
                    <div class="tab-pane fade" id="nav-review" role="tabpanel" aria-labelledby="nav-review-tab" style="padding : 2em;">
                        <!-- 후기 NAV 영역 -->
                        <!-- 후기 신규 등록 -->
                        {% if user.is_authenticated %}
                        <div>
                            <form class="row g-2" action="{% url 'restaurant:create_restaurant_comment' restaurant.id %}" method="POST" enctype="multipart/form-data">
                                {%csrf_token%}
                                    <select class="form-select" name="review_menu" id="review_menu">
                                        {% for food in menu_list %}
                                            <option value="{{ food.id }}">{{ food.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <input type="file" class="form-control" id="review_image" name="review_image">
                                    <textarea class="form-control" name="review_content" id="review_content" rows="2" placeholder="20자 이상으로 작성해주셔야 이벤트에 등록할 수 있습니다:)"></textarea>
                                <input type="submit" value="확인">
                            </form>
                        </div>
                        {% endif %}

                        <!-- 후기 목록 -->
                        <div style="padding-top: 2em;">
                            <table width="100%;">
                            {% for comment in comment_list %}
                                <tr>
                                    <td style="padding:5px;">{{ comment.user.username }}</td>
                                    <td style="padding:5px;" align="right">
                                        <!-- 추천 -->
                                        {% with comment_like_users=comment.like_users.all %}
                                            {% if request.user in comment_like_users %}
                                                <a href="{% url 'restaurant:likeComment' restaurant.id comment.id %}">
                                                <i class="fas fa-thumbs-up" style="color: red;"></i>
                                                </a>
                                            {% elif user.is_authenticated %}
                                                <a href="{% url 'restaurant:likeComment' restaurant.id comment.id %}">
                                                <i class="far fa-thumbs-up" style="color: gray;"></i>
                                                </a>
                                            {% else %}
                                                <i class="far fa-thumbs-up" style="color: gray;"></i>
                                            {% endif %}
                                            {{ comment.like_users.count }}
                                        {% endwith %}
                                        <!-- 비추천 -->
                                        {% with comment_hate_users=comment.hate_users.all %}
                                            {% if request.user in comment_hate_users %}
                                                <a href="{% url 'restaurant:hateComment' restaurant.id comment.id %}">
                                                <i class="fas fa-thumbs-down" style="color: blue;"></i>
                                                </a>
                                            {% elif user.is_authenticated %}
                                                <a href="{% url 'restaurant:hateComment' restaurant.id comment.id %}">
                                                <i class="far fa-thumbs-down" style="color: gray;"></i>
                                                </a>
                                            {% else %}
                                                <i class="far fa-thumbs-down" style="color: gray;"></i>
                                            {% endif %}
                                            {{ comment.hate_users.count }}
                                        {% endwith %}
                                    </td>
                                </tr>
                                <tr style="border-bottom: 1px solid #dee2e6;">
                                    <td style="width: 70%; padding:15px;">
                                        [{{ comment.menu.name }}] {{ comment.content }}
                                    </td>
                                    <td style="width: 30%; padding:15px;" align="right">
                                        {% if comment.thumbnail %}
                                            <img src="{{ comment.thumbnail.url }}" style="max-width: 100%; border-radius: 5px;">
                                        {% else %}
                                            <img src="{% static 'img/gallery/logo_black.png' %}" style="max-width: 100%; border-radius: 5px;">
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </table>
                        </div>
                    </div>
                    <!-- END 후기 TAB 영역 -->
                </div>
                <!-- END 메뉴, 후기 NAV TAB 영역 -->
            </div>
        </div>
    </div>
</section>


{% endblock %}

restaurant/templates/restaurant/search.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/components/restaurant_search.css'%}">

{% if restaurant_list %}
<section id="testimonial">
  <div class="container">

        <form action="{% url 'restaurant:search_resturant' %}" method="GET" class="row gx-2 gy-2 align-items-center mb-3">
            <table width="90%" align="center">
                <tr>
                    <td width="70%;">
                        <i class="fas fa-search input-box-icon text-primary"></i>
                        <input
                            class="col-lg-3 form-control border-0 input-box bg-100"
                            style="display: inline; width:80%;"
                            type="search"
                            placeholder="Search Restaurant"
                            aria-label="Search"
                            name="search_key"
                            id="search_key"
                            value="{{ search_key }}"
                        />
                    </td>
                    <td width="20%;">
                        <button class="btn btn-danger" type="submit" style="padding: 0.5rem;">
                            검색
                        </button>
                    </td>
                </tr>
            </table>
        </form>

        <!-- 식당 리스트 -->
        <table width="90%" align="center">
        {% for restaurant in pages %}
            <tr style="border-bottom: 1px solid #dee2e6;">
                <td style="width: 30%; padding: 10px;">
                    <a href="{{ restaurant.get_absolute_url }}" >
                        {% if restaurant.thumbnail %}
                            <img src="{{ restaurant.thumbnail.url }}" style="max-width: 80%; border-radius: 5px;">
                        {% else %}
                            <img src="{% static 'img/gallery/logo_black.png' %}" style="max-width: 80%; border-radius: 5px;">
                        {% endif %}
                    </a>
                </td>
                <td style="width: 70%; padding: 15px;">
                    <a href="{{ restaurant.get_absolute_url }}" >
                        <h5>{{ restaurant.name }}</h5>
                        <p class="mb-1">
                            <span class="text-primary fs--1 me-1">
                                <i class="fas fa-location-arrow"></i>
                            </span>
                            {{ restaurant.location }}
                        </p>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </table>

  </div>
</section>
{% else %}
<p>"{{ search_key }}"의 검색 결과가 없습니다.</p>
{% endif %}

<div class="page middle">
    {% if pages.has_previous %}
    <a href="?page={{pages.previous_page_number}}" class="page_click active">◀ 이전</a>
    {% else %}
    <a class="page_click nonactive">◀ 이전</a>
    {% endif %}

    {% if pages.has_next %}
    <a href="?page={{pages.next_page_number}}" class="page_click active">다음 ▶</a>
    {% else %}
    <a class="page_click nonactive">다음 ▶</a>
    {% endif %}
</div>

<script type="text/javascript">
  $('.responsive').slick({
      dots: false,
      infinite: false,
      speed: 300,
      slidesToShow: 6,
      slidesToScroll: 1,
      responsive: [
          {
              breakpoint: 1024,
              settings: {
                  slidesToShow: 6,
                  slidesToScroll: 1
              }
          },
          {
              breakpoint: 600,
                  settings: {
                      slidesToShow: 4,
                      slidesToScroll: 2
                  }
              },
          {
          breakpoint: 480,
              settings: {
                  slidesToShow: 4,
                  slidesToScroll: 2
              }
          }
      ]
  });
</script>

{% endblock %}