board/urls.py
from django.urls import path
from .views import *

app_name = "board"
urlpatterns = [
    path('board_main',board_main,name='board_main'),
    path('request_detail/<str:id>',request_detail,name='request_detail'),
    path('request_edit/<str:id>',request_edit,name='request_edit'),
    path('request_update/<str:id>',request_update,name='request_update'),
    path('request_delete/<str:id>',request_delete,name='request_delete'),
    path('request_create',request_create,name='request_create'),
    path('request_new',request_new,name='request_new'),
]

podongpodong/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from podongpodong import views


urlpatterns = [
    path('admin/', admin.site.urls), # admin
    path('', views.main, name="main"),
    path('restaurant/', include('restaurant.urls')), # 식당
    path('review/', include('review.urls')),
    path('users/',include('users.urls')),
    path('accounts/',include('allauth.urls')),
    path('board/',include('board.urls')), # 건의함
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "restaurant"
urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='restaurant_list'),
    path('<str:id>/', RestaurantList, name='restaurant_list2'),
    path('detail/<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    path('detail/<int:pk>/follow', followRestaurant, name='followRestaurant'),
    path('detail/<int:pk>/commentLike/<int:id>', likeComment, name='likeComment'),
    path('detail/<int:pk>/commentHate/<int:id>', hateComment, name='hateComment'),
    path('<int:id>/create_comment', CreateRestaurantComment, name='create_restaurant_comment'),

    # 식당 검색
    path('restaurant/search/', SearchRestaurant, name='search_resturant'),
]

review/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "review"
urlpatterns = [
    path('',views.review,name='review'),
    path('<int:id>/',views.filter,name='filter'),

    # 검색
    path('search/', views.SearchReview, name="SearchReview")
]

review/models.py
from django.db import models

# Create your models here.

review/views.py
from typing import Counter
from django.shortcuts import get_object_or_404, render, redirect
from django.shortcuts import render
from restaurant.models import Comment, Category

from django.db.models import Q
from django.core.paginator import Paginator
from django.db.models import Count

# Create your views here.

def review(request):
    reviews = Comment.objects.all().annotate(like_count = Count('like_users')).order_by("-like_count", "-created_at")
    category = Category.objects.all()
    user = request.user
    paginator = Paginator(reviews, 10)
    page = request.GET.get("page") or 1
    pages = pages = paginator.get_page(page)
    context = {
        'reviews':reviews,
        'user':user,
        'category':category,
        'pages':pages,
    }
    return render(request, "review.html",context)

def filter(request, id): 
    reviews = Comment.objects.filter(restaurant__category__id__contains = id).annotate(like_count = Count('like_users')).order_by("-like_count", "-created_at")
    category = Category.objects.all()
    user = request.user
    paginator = Paginator(reviews, 10)
    page = request.GET.get("page") or 1
    pages = pages = paginator.get_page(page)
    context = {
        'reviews':reviews,
        'user':user,
        'category':category,
        'pages':pages,
    }
    return render(request, "filter.html",context)

def SearchReview(request):
    search_category = request.GET.get('category')
    search_key = request.GET.get('search_key')
    reviews = Comment.objects.all().annotate(like_count = Count('like_users')).order_by("-like_count", "-created_at")
    category = Category.objects.all()
    if search_key:
        if search_category == "restaurant":
            reviews = reviews.filter(Q(restaurant__name__icontains=search_key))
        elif search_category == "menu":
            reviews = reviews.filter(Q(menu__name__icontains=search_key))
        elif search_category == "title":
            reviews = reviews.filter(Q(content__icontains=search_key))
        else:
            reviews = reviews.filter(Q(content__icontains=search_key)|Q(restaurant__name__icontains=search_key)|Q(menu__name__icontains=search_key)|Q(content__icontains=search_key))
    paginator = Paginator(reviews, '10')
    page = request.GET.get("page")
    pages = paginator.get_page(page)
    context = {
        'reviews': reviews,
        'category': category, 
        'search_key': search_key, 
        'pages': pages,
        'search_category':search_category,
    }
    return render(request, "search.html", context)

review/templates/filter.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="py-0 bg-primary-gradient">
    <div class="container">
      <div class="row justify-content-center g-0">
        <div class="col-xl-9">
          <div class="col-lg-6 text-center mx-auto mb-3 mb-md-5 mt-4">
            <h5 class="fw-bold text-danger fs-3 fs-lg-5 lh-sm my-6" style="margin-top:8rem !important;">식당 후기 보기</h5>
          </div>
          <div class="col-lg-7 mx-auto text-center mb-6">
            <div class="responsive">
              <a href="{% url 'review:review' %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                전체
            </a>
            {% for category in category %}
                <a href="{% url 'review:filter' category.id %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                    {{ category.name }}
                </a>
            {% endfor %}
            </div>
        </div>
        <form action="{% url 'review:SearchReview' %}" method="GET" class="row gx-2 gy-2 align-items-center">
          <div class="col-lg-1">
          <select name="category" id="category">
            <option value = "all" selected>모두</option>
            <option value="title">내용</option>
            <option value="menu">메뉴</option>
            <option value="restaurant">식당</option>
          </select>
          </div>
          <div class="col-lg-3 input-group-icon pe-2">
            <i class="fas fa-search input-box-icon text-primary"></i>
            <input
              class="col-lg-3 form-control border-0 input-box bg-100"
              type="search"
              placeholder="Search Review"
              aria-label="Search"
              name="search_key"
              id="search_key"
              value="{{ search_key }}"
            />
          </div>
          <div class="col-lg-2">
            <button class="btn btn-danger" style="padding:0.5rem;" type="submit">
              검색
            </button>
          </div>
        </form>
        <!--모바일 화면에만 보임-->
         <table class="table table-striped d-block d-sm-none">
          <thead>
              <tr class="thead col-xs-1">
                <th width=15%>식당</th>
                <th width=20%>메뉴</th>
                <th width=25%>내용</th>
                <th width=14%>좋아요</th>
              </tr>
          </thead>
          <tbody>
          {% for review in reviews %}
              <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                  <td>{{review.restaurant.name}}</td>
                  <td>{{review.menu|truncatechars:4}}</td>
                  <td>{{review.content|truncatechars:7}}</td>
                  <td>{{review.like_users.count}}</td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
        <!--모바일 이외의 화면에서만 보임-->
        <table class="table table-striped d-none d-sm-table">
          <thead>
              <tr class="thead col-xs-1">
                  <th width=10%>순번</th>
                  <th width=15%>식당</th>
                  <th width=15%>메뉴</th>
                  <th width=30%>내용</th>
                  <th width=15%>작성자</th>
                  <th>좋아요</th>
              </tr>
          </thead>
          <tbody>
          {% for review in reviews %}
              <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                  <td>{{ forloop.revcounter }}</td>
                  <td>{{review.restaurant.name}}</td>
                  <td>{{review.menu}}</td>
                  <td>{{review.content|truncatechars:15}}</td>
                  <td>{{review.user}}</td>
                  <td>{{review.like_users.count}}</td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
        </div>
      </div>
    </div>
  </section> 
  <div class="page middle">
    {% if pages.has_previous %}
    <a href="?page={{pages.previous_page_number}}" class="page_click active">◀ 이전</a>
    {% else %}
    <a class="page_click nonactive">◀ 이전</a>
    {% endif %}

    {% if pages.has_next %}
    <a href="?page={{pages.next_page_number}}" class="page_click active">다음 ▶</a>
    {% else %}
    <a class="page_click nonactive">다음 ▶</a>
    {% endif %}
</div>
  <style>
    .thead {
      border-bottom:#F17228;
    }
    .bnt {
      background-color: #F17228; 
      color: white; 
      font-weight: bold; 
      border: none; 
      border-radius: 5px; width: 80px;
    }
    section {
  margin-top: 100px;
  min-height: 400px;
}

.middle{
  text-align: center;
  margin-bottom: 5%;
}
.middle a {
  margin: 20px;
  padding: 10px;
}
.number {
  font-size: 20px;
}
.active {
  transition-duration: 0.2s;
}
.active:hover {
  color: #FFB310;
  cursor: pointer;
}
.nonactive {
  color: #a4a4a4;
  cursor: pointer;
}
  </style>
  <script type="text/javascript">
    $('.responsive').slick({
        dots: false,
        infinite: false,
        speed: 300,
        slidesToShow: 6,
        slidesToScroll: 1,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 6,
                    slidesToScroll: 1
                }
            },
            {
                breakpoint: 600,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 2
                    }
                },
            {
            breakpoint: 480,
                settings: {
                    slidesToShow: 4,
                    slidesToScroll: 2
                }
            }
        ]
    });
</script>
{% endblock %}

review/templates/review.html
{% extends 'base.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static 'css/components/review.css' %}" />
<section class="py-0 bg-primary-gradient">
    <div class="container">
      <div class="row justify-content-center g-0">
        <div class="col-xl-9">
          <div class="col-lg-6 text-center mx-auto mb-3 mb-md-5 mt-4">
            <h5 class="fw-bold text-danger fs-3 fs-lg-5 lh-sm my-6" style="margin-top:8rem !important;">식당 후기 보기</h5>
          </div>
          <div class="col-lg-7 mx-auto text-center mb-6">
                <div class="responsive">
                  <a href="{% url 'review:review' %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                    전체
                </a>
                {% for category in category %}
                    <a href="{% url 'review:filter' category.id %}" style="border:1px solid #ced4da; border-radius: 4px; margin: 5px;">
                        {{ category.name }}
                    </a>
                {% endfor %}
                </div>
          </div>
          <form action="{% url 'review:SearchReview' %}" method="GET" class="row gx-2 gy-2 align-items-center">
            <div class="col-lg-1">
            <select name="category" id="category">
              <option value = "all" selected>모두</option>
              <option value="title">내용</option>
              <option value="menu">메뉴</option>
              <option value="restaurant">식당</option>
            </select>
            </div>
            <div class="col-lg-3 input-group-icon pe-2">
              <i class="fas fa-search input-box-icon text-primary"></i>
              <input
                class="col-lg-3 form-control border-0 input-box bg-100"
                type="search"
                placeholder="Search Review"
                aria-label="Search"
                name="search_key"
                id="search_key"
                value="{{ search_key }}"
              />
            </div>
            <div class="col-lg-2">
              <button class="btn btn-danger" style="padding:0.5rem;" type="submit">
                검색
              </button>
            </div>
          </form>
          <!--모바일 화면에만 보임-->
          <table class="table table-striped d-block d-sm-none">
            <thead>
                <tr class="thead col-xs-1">
                    <th width=15%>식당</th>
                    <th width=20%>메뉴</th>
                    <th width=25%>내용</th>
                    <th width=14%>좋아요</th>
                </tr>
            </thead>
            <tbody>
            {% for review in pages %}
                <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                    <td>{{review.restaurant.name}}</td>
                    <td>{{review.menu|truncatechars:4}}</td>
                    <td>{{review.content|truncatechars:7}}</td>
                    <td>{{review.like_users.count}}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
          <!--모바일 이외의 화면에서만 보임-->
          <table class="table table-striped d-none d-sm-table">
            <thead>
                <tr class="thead col-xs-1">
                    <th width=10%>순번</th>
                    <th width=15%>식당</th>
                    <th width=15%>메뉴</th>
                    <th width=30%>내용</th>
                    <th width=15%>작성자</th>
                    <th >좋아요</th>
                </tr>
            </thead>
            <tbody>
            {% for review in pages %}
                <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                    <td>{{ forloop.revcounter }}</td>
                    <td>{{review.restaurant.name}}</td>
                    <td>{{review.menu}}</td>
                    <td>{{review.content|truncatechars:15}}</td>
                    <td>{{review.user}}</td>
                    <td>{{review.like_users.count}}</td>
                </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
      </div>
    </div>
  </div>
</section> 
<div class="page middle">
    {% if pages.has_previous %}
    <a href="?page={{pages.previous_page_number}}" class="page_click active">◀ 이전</a>
    {% else %}
    <a class="page_click nonactive">◀ 이전</a>
    {% endif %}

    {% if pages.has_next %}
    <a href="?page={{pages.next_page_number}}" class="page_click active">다음 ▶</a>
    {% else %}
    <a class="page_click nonactive">다음 ▶</a>
    {% endif %}
</div>
  <style>
    .thead {
      border-bottom:#F17228;
    }
    .bnt {
      background-color: #F17228; 
      color: white; 
      font-weight: bold; 
      border: none; 
      border-radius: 5px; width: 80px;
    }
    section {
  margin-top: 100px;
  min-height: 400px;
}
.middle{
  text-align: center;
  margin-bottom: 5%;
}
.middle a {
  margin: 20px;
  padding: 10px;
}
.number {
  font-size: 20px;
}
.active {
  transition-duration: 0.2s;
}
.active:hover {
  color: #FFB310;
  cursor: pointer;
}
.nonactive {
  color: #a4a4a4;
  cursor: pointer;
}
  </style>
  <script type="text/javascript">
    $('.responsive').slick({
        dots: false,
        infinite: false,
        speed: 300,
        slidesToShow: 6,
        slidesToScroll: 1,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 6,
                    slidesToScroll: 1
                }
            },
            {
                breakpoint: 600,
                    settings: {
                        slidesToShow: 4,
                        slidesToScroll: 2
                    }
                },
            {
            breakpoint: 480,
                settings: {
                    slidesToShow: 4,
                    slidesToScroll: 2
                }
            }
        ]
    });
</script>
{% endblock %}

review/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/components/review_search.css' %}">

<section class="py-0 bg-primary-gradient">
    <div class="container">
        <div class="row justify-content-center g-0">
            <div class="col-xl-9">
                <p id="searchkey">"{{ search_key }}"의 검색 결과입니다.</p>
                <form style="margin-top: 10%;" action="{% url 'review:SearchReview' %}" method="GET" class="row gx-2 gy-2 align-items-center">
                    <div class="col-lg-1">
                    <select name="category" id="category">
                    {% if search_category == "title" %}
                        <option  value="all">모두</option>
                        <option value="title" selected>내용</option>
                        <option value="menu">작성자</option>
                        <option value="restaurant">식당</option>
                    {% elif search_category == "menu" %}
                        <option  value="all">모두</option>
                        <option value="title">내용</option>
                        <option value="menu" selected>작성자</option>
                        <option value="restaurant">식당</option>
                    {% elif search_category == "restaurant" %}
                        <option  value="all">모두</option>
                        <option value="title">내용</option>
                        <option value="menu">작성자</option>
                        <option value="restaurant" selected>식당</option>
                    {% else %}
                        <option value="all" selected>모두</option>
                        <option value="title">내용</option>
                        <option value="menu">작성자</option>
                        <option value="restaurant">식당</option>
                    {% endif %}
                    </select>
                    </div>
                    <div class="col-lg-3 input-group-icon pe-2">
                      <i class="fas fa-search input-box-icon text-primary"></i>
                      <input
                        class="col-lg-3 form-control border-0 input-box bg-100"
                        type="search"
                        placeholder="Search Review"
                        aria-label="Search"
                        name="search_key"
                        id="search_key"
                        value="{{ search_key }}"
                      />
                    </div>
                    <div class="col-lg-2">
                      <button class="btn btn-danger" style="padding:0.5rem;" type="submit">
                        검색
                      </button>
                    </div>
                  </form>
                  <!--모바일에 노출되는 테이블-->
                  <table class="table table-striped d-block d-sm-none">
                    <thead>
                        <tr class="thead col-xs-1">
                            <th width=15%>식당</th>
                            <th width=20%>메뉴</th>
                            <th width=25%>내용</th>
                            <th width=14%>좋아요</th>
                        </tr>
                    </thead>
                    {% if pages %}
                    <tbody>
                    {% for review in pages %}
                        <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                            <td>{{review.restaurant.name}}</td>
                            <td>{{review.menu|truncatechars:4}}</td>
                            <td>{{review.content|truncatechars:7}}</td>
                            <td>{{review.like_users.count}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                  </table>
                  <!--모바일 이외의 기기에서 노출되는 화면-->
                  <table class="table table-striped d-none d-sm-block">
                    <thead>
                        <tr class="thead col-xs-1">
                            <th width=10%>순번</th>
                            <th width=15%>식당</th>
                            <th width=15%>메뉴</th>
                            <th width=30%>내용</th>
                            <th width=15%>작성자</th>
                            <th>좋아요</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for review in pages %}
                        <tr onclick="location.href='{% url 'restaurant:restaurant_detail' review.restaurant.id %}'">
                            <td>{{ forloop.revcounter }}</td>
                            <td>{{review.restaurant.name}}</td>
                            <td>{{review.menu}}</td>
                            <td>{{review.content|truncatechars:15}}</td>
                            <td>{{review.user}}</td>
                            <td>{{review.like_users.count}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    {% else %}
                    {% endif %}
                  </table>
            </div>
        </div>
    </div>
</section>

<div class="page middle">
    {% if pages.has_previous %}
    <a href="?page={{pages.previous_page_number}}" class="page_click active">◀ 이전</a>
    {% else %}
    <a class="page_click nonactive">◀ 이전</a>
    {% endif %}

    {% if pages.has_next %}
    <a href="?page={{pages.next_page_number}}" class="page_click active">다음 ▶</a>
    {% else %}
    <a class="page_click nonactive">다음 ▶</a>
    {% endif %}
</div>

{% endblock %}